### ISSUE TITLE
Regexp matching might map incorrectly

### ISSUE THREAD

**Issue by luislavena** [vladfaust/http-multiserver.cr#2]
Hello,

Thanks for releasing this shard and you contributions to Crystal!

I was checking this out and noticed that under some scenarios, some mappings might be incorrectly _mapped_ (no pun intended).

```crystal
map = {
  "/foo" => foo_server,
  "/bar" => bar_server
}
```

When using `/bar/foo` it will find `/foo` as matching (because uses `%r{/foo}`) and map to `foo_server` instead of `bar_server` one.

Not sure if this is intended behavior, so perhaps will be good to mention this in the docs or adjust generated regexp to use anchors (start line, for example).

Once again, thank you for your contributions and releasing this shard! ❤️ ❤️ ❤️

**Comment by vladfaust** [comment]
@luislavena,

I'm happy to see a real Crystal contributor playing with my code! Thank **you** for developing the language itself.

I see the issue and I agree that using start anchor is a better behaviour.
